### ISSUE TITLE
Actor-based integration tests

### ISSUE THREAD

**Issue by thomaseizinger** [get10101/itchysats#231]
Currently, we have to manually test the entire application if we want to verify that it still works.

We need automated tests that operate on an actor level.

Some ideas:

- Create an abstraction called an "actor system" that initializes and wires a set of actors together
- Said actor system should be generic over blockchain communication
- Communication between maker and taker could be generic over IO (by directly wiring the two actors together) or also happen on a random port (listen on 0)
- Tests **must** be fast, no communication with blockchain nodes. This will likely require the wallet to be generic over the client. Possible introducing a dedicated `Wallet` actor might also help as it would allow us to swap out the actor that handles blockchain communication for the tests

**Comment by thomaseizinger** [comment]
In order to resolve this we may need to choose, which actors we want to "stub" in the tests and thus, have only those addresses be generic over the actor type.

In other words, the `monitor::Actor` can likely know that it will always send message to the `cfd::Actor` whereas for the tests, we probably want to stub the `monitor::Actor` within `cfd::Actor` and thus have that address be generic.

I guess this will require two monitoring actors instead of one (one per daemon) but we can just share the code on a lower-level and have the actor just be glue code.

**Comment by da-kami** [comment]
Everything concerning the test framework as described in this ticket is done with merging #428 - however, we did not add a whole lot of tests yet. 

@klochowicz should we close this ticket or just keep it open until we have some more test coverage?

**Comment by klochowicz** [comment]
I would be in favour of closing this ticket and creating a few dedicated, actionable ones for increasing the test coverage in the areas we care about (e.g. collab settlement, non-collab settlement, restarting during various stages)
