### ISSUE TITLE
Failure to PUT new offers on the maker

### ISSUE THREAD

**Issue by klochowicz** [get10101/itchysats#2452]
~~Projection actor is down~~ One of the actors is disconnected, and new HTTP requests fail, preventing updating the state with new offers.

link:

https://itchysats.grafana.net/explore?orgId=1&left=%7B%22datasource%22:%22grafanacloud-itchysats-traces%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22queryType%22:%22traceId%22,%22serviceName%22:%22maker%22,%22search%22:%22error%3Dtrue%22,%22query%22:%2263c4506d3c2d7eb6f7e6cd0a0dc21142%22%7D%5D,%22range%22:%7B%22from%22:%221658171999622%22,%22to%22:%221658175968042%22%7D%7D&right=%7B%22datasource%22:%22grafanacloud-itchysats-traces%22,%22queries%22:%5B%7B%22query%22:%2263c4506d3c2d7eb6f7e6cd0a0dc21142%22,%22queryType%22:%22traceId%22,%22refId%22:%22A%22%7D%5D,%22range%22:%7B%22from%22:%221658171999622%22,%22to%22:%221658175968042%22%7D%7D

**Comment by bonomat** [comment]
How do you know from this trace that the projection is down? 

From what I can tell the error is one layer up and `"daemon::projection::Update<core::option::Option<model::cfd::MakerOffers>>"` was fine.


![Explore-grafanacloud-itchysats-traces-Grafana](https://user-images.githubusercontent.com/224613/179635307-1f9f5415-bdd3-453c-812c-ea35837db914.png)

**Comment by Restioson** [comment]
Hmm, you are right I think - I suppose `send_async_safe` should log the actor & message type in the case of disconnection.

**Comment by klochowicz** [comment]
@bonomat updated description; indeed we can't infer what I have written from the trace itself; it just shows that one of the actors was disconnected.

**Comment by klochowicz** [comment]
Looking at the logs, there was a panic in the maker caused by failed vergen parsing. Fix for that panic is here: #2477 

I'm working on resilient offer publishing now.
