### ISSUE TITLE
Replace `SigHashExt` with usage of `ThirtyTwoByteHash`

### ISSUE THREAD

**Issue by luckysori** [get10101/itchysats#27]
Blocked by:

- [x] https://github.com/ElementsProject/rust-secp256k1-zkp/pull/30
- [ ] https://github.com/ElementsProject/rust-secp256k1-zkp/issues/32
- [x] https://github.com/rust-bitcoin/rust-secp256k1/pull/326

**Comment by thomaseizinger** [comment]
This code now lives in `maia` I believe so we now longer need to track this here.
