### ISSUE TITLE
Provide payout information after closing CFD with a collaborative settlement

### ISSUE THREAD

**Issue by klochowicz** [get10101/itchysats#297]
Pass in the necessary information for the UI to show the payout.

**Comment by klochowicz** [comment]
this also matters for `margin` calculation in the event when we closed a CFD with collaborative settlement instead of attestation.

**Comment by klochowicz** [comment]
@da-kami part of me thinks it might be cleaner with a different `Closed` cfd state actually, as it would be easier to read, e.g.
 `ClosedNonCollab` would always have `attestation`, and `ClosedCollab` would always have `collab_settlement`. no need for yet another enum perhaps....

**Comment by thomaseizinger** [comment]
Is this done @klochowicz ?

**Comment by klochowicz** [comment]
I believe it was done in https://github.com/comit-network/hermes/pull/315 by @da-kami . Closing the issue.
