### ISSUE TITLE
Ability to start the taker without the maker daemon

### ISSUE THREAD

**Issue by da-kami** [get10101/itchysats#30]
The taker daemon should be more resilient upon startup. If the maker is not available it should print a message like `maker currently not available, retrying connection setup in x seconds...` and then retry setting up the connection.

**Comment by thomaseizinger** [comment]
To make this work you will need an indirection or some other mechanism to make the branch for sending and receiving messages in the `select!` macro pluggable / toggable. Creating another channel that serves as an indirection would probably work.

**Comment by thomaseizinger** [comment]
This is more of a nice to have than absolutely necessary. Removed from epic.

**Comment by klochowicz** [comment]
I believe this was done in: https://github.com/comit-network/hermes/pull/61

I'm marking it as closed, as I don't think we need more resiliency for the MVP than that.

**Comment by thomaseizinger** [comment]
Well, technically you still cannot start the taker without the maker. We are just delaying the start up until the maker is online.
