### ISSUE TITLE
Auto-reject on any order

### ISSUE THREAD

**Issue by da-kami** [get10101/itchysats#323]
Current behavior: Maker rejects any order that the taker sends. 
Weird side effect: Somehow the cfd ends up being in two groups at the same time (!) in the UI, it is `Closed` and `Opening`.

The Maker does not see anything in the UI, never even know that there was an error.

**Comment by bonomat** [comment]
> Current behavior: Maker rejects any order that the taker sends.

Do you mean the Maker rejects **all** orders? This I was not able to reproduce. 

I can reproduce the error of seeing the same order in multiple tabs, this might be related to #326

**Comment by bonomat** [comment]
I was able to reproduce the problem of "any" order being rejected if the quantity was not changed: see #330 and it's fix #331

**Comment by da-kami** [comment]
> Do you mean the Maker rejects all orders? This I was not able to reproduce.

Yes, I was somehow in a state where no matter what I sent I always got a reject back.

It might be that this ticket is actually not a problem (anymore), but the problem is actually this one: https://github.com/comit-network/hermes/issues/324 (which is is cause by the offer not being removed after we send an error-reject)

And I am not sure what side effects this might have. https://github.com/comit-network/hermes/issues/324 is not easy to fix though - one way I see is, removing the offer in case of an error and just putting a new one with the same parameter up. 
The underlying problem is, that the taker creates a `Cfd` that is then rejected. Since that `Cfd` is in the database we cannot take this offer another time, because of the `1:1` relationship between cfd and offer. The maker currently always has to take care of removing the `Cfd` after any interaction with the taker. Not optimal, but that's what the current logic is :/
