### ISSUE TITLE
Calculate profit in daemon and display in UI

### ISSUE THREAD

**Issue by da-kami** [get10101/itchysats#33]
The CFD profit is dependent on the current price (calculated). We should take the current price into account for the CFD feed.

- upon CFD feed update re-calculate the profit every time
- upon price update trigger a CFD feed update

This requires some kind of price feed (from the Oracle or a component that publishes a reliable price related to the Oracle's price).

**Comment by klochowicz** [comment]
The issue is not done, the UI still does not display the profit and the calculation function is not done.

So far I only implemented passing the current price from the feed into the profit calculation function (which turned out to bea stub).
